Run Codecov

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -16,3 +16,6 @@ jobs:
         uses: GabrielBB/xvfb-action@v1.4
         with:
           run: npm test
+      - run: find .
+      - name: Codecov
+        run: bash <(curl -s https://codecov.io/bash) -f coverage/coverage.json || echo 'Codecov upload failed'
